// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJbkkK4IEsT6q-9tqIKKEdlCs6Oi2hvwA',
    appId: '1:734363675124:web:3fc3db1dd2a3a23a90b1a1',
    messagingSenderId: '734363675124',
    projectId: 'modern-login-ui-flutter',
    authDomain: 'modern-login-ui-flutter.firebaseapp.com',
    storageBucket: 'modern-login-ui-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBU-QmUxzOcykivWZv4DOSSS9Gsc9x8b3o',
    appId: '1:734363675124:android:7c89e75be1bcf07d90b1a1',
    messagingSenderId: '734363675124',
    projectId: 'modern-login-ui-flutter',
    storageBucket: 'modern-login-ui-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8Fq_nofQ9mLQ4VTc5vYYKxkokhI0EZhQ',
    appId: '1:734363675124:ios:5c82f6215aa874a990b1a1',
    messagingSenderId: '734363675124',
    projectId: 'modern-login-ui-flutter',
    storageBucket: 'modern-login-ui-flutter.appspot.com',
    iosClientId: '734363675124-3fc5pnh31q7js3go7r8raqo6q8fe034e.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginUiPage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8Fq_nofQ9mLQ4VTc5vYYKxkokhI0EZhQ',
    appId: '1:734363675124:ios:5c82f6215aa874a990b1a1',
    messagingSenderId: '734363675124',
    projectId: 'modern-login-ui-flutter',
    storageBucket: 'modern-login-ui-flutter.appspot.com',
    iosClientId: '734363675124-3fc5pnh31q7js3go7r8raqo6q8fe034e.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginUiPage',
  );
}
